# Your Name or Company
title: Katie Deaven

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: I am a Ph.D. student at the University of Wisconsin-Madison. My main research interests are in philosophy of science and philosophy of biology. My dissertation focuses on the explanatory and ontological puzzles concerning evolvability, a disposition for populations to evolve in various ways. I defend a metaphysically robust account of evolvability that allows evolutionary biologists and philosophers to make counterfactual claims about how a population might have evolved differently. My other research projects also use case studies in evolutionary biology as a way of making progress in more general disputes in philosophy of science.

# Add your social links
social:
  - platform: kdeaven@wisc.edu
    url: mailto:kjdeaven@wisc.edu
  - platform: Check out my CV
    url: /files/cv.pdf

professional:
  - title: About Me
    url: /  
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: Public Philosophy
    url: /mpp/

research:
    title: Research
    overview_content: HERE IS MY OVERVIEW gdsagdfsahgdjskalhgdjskal ghfdjksal ghdjskal fghdjska lfhdjsak flhdjsa kflhdsjak fldhsaj fkgldhsaj lgfhdsja kglfdhsaj gkldfhsa gjkldfa h.
    review_content: HERE IS MY Cfjndsaiogjfdea kl;grjeeiwak g;jrekas ;gfjdskal; gjdf
    progress_content: GDHASgreawqog rjekagkdflshaj; tgriwaqt;gjrie agjdfisak g;fr4ejiwa ogprjewa

teaching:
    title: Teaching
    overview_content: blah2
    courses_content: blah2

mpp:
    title: Public Philosophy
    the_kids_content: blah3
    facilitator_content: blah3
    
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

other_text_position: center # left, right or center
