# Your Name or Company
title: Katie Deaven

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: I am a Ph.D. student at the University of Wisconsin-Madison.

My main research interests are in philosophy of science and philosophy of biology. My dissertation focuses on the explanatory and ontological puzzles concerning evolvability, a disposition for populations to evolve in various ways. I defend a metaphysically robust account of evolvability that allows evolutionary biologists and philosophers to make counterfactual claims about how a population might have evolved differently. My other research projects also use case studies in evolutionary biology as a way of making progress in more general disputes in philosophy of science.


# Add your social links
social:
  - platform: email (kdeaven@wisc.edu)
    url: kjdeaven@wisc.edu
  - platform: Check out my CV
    url: https://facebook.com/luigibytes


# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
