# Your Name or Company
title: Katie Deaven

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: I am a Ph.D. student at the University of Wisconsin-Madison. My areas of specialization are philosophy of science and philosophy of biology, with areas of concentration in epistemology, metaphysics, ethics, and public philosophy. My research focuses on the explanatory and ontological puzzles concerning evolvability, a disposition for populations to evolve in various ways. In my dissertation, I defend a metaphysically robust account of evolvability that allows evolutionary biologists and philosophers to make counterfactual claims about how a population might have evolved differently.

# Add your social links
social:
  - platform: Email (kdeaven@wisc.edu)
    url: mailto:kjdeaven@wisc.edu
  - platform: Check out my CV
    url: /files/cv.pdf

professional:
  - title: About Me
    url: /  
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: Public Philosophy
    url: /mpp/

research:
    title: Research
    overview_content: My main research interests are in philosophy of science and philosophy of biology. My dissertation focuses on the explanatory and ontological puzzles concerning evolvability, a disposition for populations to evolve in various ways. I defend a metaphysically robust account of evolvability that allows evolutionary biologists and philosophers to make counterfactual claims about how a population might have evolved differently. My other research projects also use case studies in evolutionary biology as a way of making progress in more general disputes in philosophy of science.
    review_content:
      title: Relative Significance Controversies in Evolutionary Biology
      content: Scientists engage in relative significance controversies when they investigate the importance of a cause in producing a phenomenon of interest. Some philosophers have questioned the epistemic value of engaging in these controversies. In this paper, I present a taxonomy outlining the conditions under which questions of causal importance may arise. I then show how engaging in these different kinds of controversies may inform scientists’ research. Using the historical examples of the neutralist-selectionist controversy in molecular evolution and the group selection controversy, I illustrate how these controversies help scientists form predictions about new instances of the phenomenon of interest, refine our understanding of causes of the phenomenon of interest, and improve explanations that postulate causal structures. 
    progress_content:
      title: Reference Class Choice and the Evolution of Senescence
      content: Researchers working on the evolution of senescence have recently responded to classical theorists, arguing that senescence is not, in fact, inevitable. Rather than responding to these theories, I argue these contemporary scholars are merely employing a different reference class, In what follows, I explore how the problem of reference class choice arises in controversies in evolutionary biology. Then, I describe different approaches to justifying choice in reference class. Finally, I explore how the problem of reference class has hindered research on the evolution of senescence and suggest some ways in which progress may be made.

teaching:
    title: Teaching
    overview_content: blah2
    courses_content: blah2

mpp:
    title: Public Philosophy
    the_kids_content: blah3
    facilitator_content: blah3
    
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

other_text_position: center # left, right or center
